-- AlterTable
ALTER TABLE `Commission_filleul` ADD COLUMN `CSPE` BOOLEAN NULL,
    ADD COLUMN `GBT` BOOLEAN NULL,
    ADD COLUMN `TURP` BOOLEAN NULL,
    ADD COLUMN `courtage` BOOLEAN NULL,
    ADD COLUMN `logiciel` BOOLEAN NULL;
